Resources:
  EC2Instance:
      Type: AWS::EC2::Instance
      Properties:
        AvailabilityZone: 'us-east-1c'
        InstanceType: t2.micro
        ImageId: ami-0b5eea76982371e91
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeType: gp3
              VolumeSize: '20'

  NewVolume:
      Type: AWS::EC2::Volume
      Properties:
        Size: 100
        AvailabilityZone: 'us-east-1c'
        Tags:
          - Key: EC2Vol
            Value: VOL2
      DeletionPolicy: Snapshot

  MountPoint:
      Type: AWS::EC2::VolumeAttachment
      Properties:
        Device: /dev/sdh
        InstanceId: 
            Ref: EC2Instance
        VolumeId: 
            Ref: NewVolume





      


